import { Inter } from "next/font/google";
import 'primereact/resources/themes/viva-light/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Аналитика",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" style={{'font-size': '14px'}}>
      <body className={`${inter.className} mx-0 my-0`}>
        {children}
      </body>
    </html>
  );
}
