import { Inter } from "next/font/google";
//import "./globals.css";
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import ReactQueryProvider from "@/components/ReactQueryProvider";
import {Splitter, SplitterPanel} from "primereact/splitter";
import {SideMenuContainer} from "@/components/layout/SideMenu"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Заебушка просто блядь охуенная",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='mx-0 my-0'>
      <Splitter className='flex h-screen'>
        <SplitterPanel minSize={5} size={15} className="flex">
          <SideMenuContainer/>
        </SplitterPanel>
        <SplitterPanel minSize={85} size={85} className="flex">
          <div>
            <ReactQueryProvider>
              {children}
            </ReactQueryProvider>
          </div>
        </SplitterPanel>
      </Splitter>
      </body>
    </html>
  );
}
