import { Inter } from "next/font/google";
//import "./globals.css";
import 'primereact/resources/themes/viva-light/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import ReactQueryProvider from "@/components/ReactQueryProvider";
import {Splitter, SplitterPanel} from "primereact/splitter";
import {SideMenuContainer} from "@/components/layout/SideMenu"
import {ScrollPanel} from "primereact/scrollpanel";
import {Suspense} from "react";
import Loading from "@/app/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Аналитика",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{'font-size': '14px'}}>
      <body className='mx-0 my-0'>
      <Splitter className='flex h-screen'>
        <SplitterPanel minSize={5} size={15}>
          <ReactQueryProvider>
            <SideMenuContainer/>
          </ReactQueryProvider>
        </SplitterPanel>
        <SplitterPanel minSize={85} size={85}>
          <div className='w-full'>
            <ScrollPanel style={{height: '99vh'}}>
              <Suspense fallback={<Loading/>}>
                <ReactQueryProvider>
                  {children}
                </ReactQueryProvider>
              </Suspense>
            </ScrollPanel>
          </div>
        </SplitterPanel>
      </Splitter>
      </body>
    </html>
  );
}
