# Generated by Django 4.2.11 on 2024-05-13 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('id_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finsite.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change', models.DateField(default=datetime.datetime(2024, 5, 13, 7, 23, 48, 673462))),
                ('amount', models.IntegerField(default=0)),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finsite.products')),
                ('id_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finsite.providers')),
            ],
        ),
        migrations.CreateModel(
            name='PriceManagments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change', models.DateField(default=datetime.datetime(2024, 5, 13, 7, 23, 48, 673178))),
                ('price', models.FloatField(default=0.0)),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finsite.products')),
            ],
        ),
        migrations.CreateModel(
            name='Keeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finsite.products')),
                ('id_storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finsite.storages')),
            ],
        ),
    ]
