# Generated by Django 4.2.11 on 2024-05-13 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanagments',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 16, 37, 46, 467875)),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 16, 37, 46, 468223)),
        ),
    ]
