# Generated by Django 4.2.11 on 2024-05-13 07:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0002_alter_pricemanagments_date_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanagments',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 16, 38, 17, 840570)),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finsite.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 16, 38, 17, 840843)),
        ),
    ]
