# Generated by Django 4.2.11 on 2024-05-13 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0003_alter_pricemanagments_date_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='keeping',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='keeping',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finsite.products', verbose_name='Номер товара'),
        ),
        migrations.AlterField(
            model_name='keeping',
            name='id_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finsite.storages', verbose_name='Номер склада'),
        ),
        migrations.AlterField(
            model_name='pricemanagments',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 16, 42, 12, 210723), verbose_name='Дата изменения цены'),
        ),
        migrations.AlterField(
            model_name='pricemanagments',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finsite.products', verbose_name='Номер товара'),
        ),
        migrations.AlterField(
            model_name='pricemanagments',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Электронная почта товара'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название поставщика'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Номер поставщика'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='building',
            field=models.CharField(max_length=50, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='city',
            field=models.CharField(max_length=25, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='district',
            field=models.CharField(max_length=50, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название склада'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 16, 42, 12, 211002), verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finsite.products', verbose_name='Номер товара'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='id_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finsite.providers', verbose_name='Номер поставщика'),
        ),
    ]
