# Generated by Django 5.0.6 on 2024-05-13 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0005_alter_pricemanagments_date_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keeping',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='keeping',
            old_name='id_storage',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='pricemanagments',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='id_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='supplies',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='supplies',
            old_name='id_provider',
            new_name='provider',
        ),
        migrations.AlterField(
            model_name='pricemanagments',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 21, 29, 31, 599814), verbose_name='Дата изменения цены'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 21, 29, 31, 600145), verbose_name='Дата поставки'),
        ),
    ]
