# Generated by Django 4.2.11 on 2024-05-16 01:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0007_pricemanagement_supplier_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanagement',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 10, 22, 53, 205026), verbose_name='Дата изменения цены'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='finsite.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_change',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 10, 22, 53, 205300), verbose_name='Дата поставки'),
        ),
    ]
