# Generated by Django 4.2.11 on 2024-05-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0008_customer_employee_order_orderline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
