# Generated by Django 5.0.6 on 2024-05-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0010_remove_productpricehistory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='finsite.product')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='finsite.storage')),
            ],
        ),
    ]
