# Generated by Django 5.0.6 on 2024-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0011_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ManyToManyField(related_name='products', through='finsite.Store', to='finsite.storage'),
        ),
        migrations.AddField(
            model_name='storage',
            name='product',
            field=models.ManyToManyField(related_name='storages', through='finsite.Store', to='finsite.product'),
        ),
    ]
