# Generated by Django 4.2.13 on 2024-05-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0012_product_storage_storage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='finsite.store'),
        ),
        migrations.AddField(
            model_name='supply',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='finsite.storage'),
        ),
    ]
