# Generated by Django 4.2.11 on 2024-05-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0014_alter_order_created_at_alter_orderline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
