# Generated by Django 4.2.11 on 2024-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsite', '0015_alter_supply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyline',
            name='unit_product_price',
            field=models.FloatField(default=0),
        ),
    ]
